/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import org.math.plot.*;
import sistemassegundoorden.*;
/*
 *
 * @author loli,mario
 */

public class Main_GUI extends javax.swing.JFrame {
    
    private int runSeconds;
    private CapturaParametros params;
    private double[] x;
    private double[] y;
    // private Plot2DPanel plot = new Plot2DPanel();
    private int systemType;
    private int tamVectorDatos;
    private Plotting plot = new Plotting();
    
    public Main_GUI() {
        initComponents();
        runSeconds = 5;
        tamVectorDatos = 51;
        x = new double[tamVectorDatos];
        y = new double[tamVectorDatos];
    }
    
    public void plotResult() {
        int cont = 0;
        double t;
        switch (systemType) {
            case 1:
                //Sistema subamortiguado
                Subamortiguado sub_amor = new Subamortiguado(params.getWn(), params.getChi());
                for (t = 0; t < runSeconds; t = t + 0.1) {
                    x[cont] = t;
                    //System.out.println(sub_amor.ftct(t));
                    y[cont] = sub_amor.ftct(t);
                    cont++;
                }
                plot.graficar(x, y);
            /*plot.addLinePlot("my plot", x, y);
             panelGrafica.add(plot);*/
            //panelGrafica.setVisible(true);
            //TODO: finsh plottinanelg
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelParams = new javax.swing.JPanel();
        labelType = new javax.swing.JLabel();
        spinnerTime = new javax.swing.JSpinner();
        labelTime = new javax.swing.JLabel();
        labelResultados = new javax.swing.JLabel();
        scrollResultados = new javax.swing.JScrollPane();
        textResultados = new javax.swing.JTextArea();
        btnRun = new javax.swing.JButton();
        labelExample = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNumerador = new javax.swing.JTextField();
        textT2 = new javax.swing.JTextField();
        panelGraphics = new javax.swing.JPanel();
        panelPlot = new javax.swing.JPanel();
        panelGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de segundo orden");
        setAlwaysOnTop(true);

        labelType.setText("Coeficientes");

        spinnerTime.setName("spinnerTime"); // NOI18N
        spinnerTime.setValue(5);
        spinnerTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerTimeStateChanged(evt);
            }
        });

        labelTime.setText("Tiempo (s):");

        labelResultados.setText("Resultados");

        textResultados.setColumns(20);
        textResultados.setRows(5);
        scrollResultados.setViewportView(textResultados);

        btnRun.setText("Comenzar");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        labelExample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/example.png"))); // NOI18N

        jLabel1.setText("Numerador:");

        jLabel4.setText("Primer grado:");

        textNumerador.setText("1.0");

        textT2.setText("1.0");

        javax.swing.GroupLayout panelParamsLayout = new javax.swing.GroupLayout(panelParams);
        panelParams.setLayout(panelParamsLayout);
        panelParamsLayout.setHorizontalGroup(
            panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelParamsLayout.createSequentialGroup()
                        .addComponent(labelTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRun))
                    .addComponent(labelType)
                    .addGroup(panelParamsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelExample))
                    .addGroup(panelParamsLayout.createSequentialGroup()
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(21, 21, 21)
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNumerador, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(textT2))))
                .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParamsLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelResultados))
                    .addGroup(panelParamsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(scrollResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelParamsLayout.setVerticalGroup(
            panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelParamsLayout.createSequentialGroup()
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelType)
                            .addComponent(labelResultados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExample)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTime)
                            .addComponent(btnRun))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parámetros", panelParams);

        javax.swing.GroupLayout panelPlotLayout = new javax.swing.GroupLayout(panelPlot);
        panelPlot.setLayout(panelPlotLayout);
        panelPlotLayout.setHorizontalGroup(
            panelPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPlotLayout.setVerticalGroup(
            panelPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGraphicsLayout = new javax.swing.GroupLayout(panelGraphics);
        panelGraphics.setLayout(panelGraphicsLayout);
        panelGraphicsLayout.setHorizontalGroup(
            panelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraphicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGraphicsLayout.setVerticalGroup(
            panelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraphicsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gráficas", panelGraphics);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerTimeStateChanged
        if ((int) spinnerTime.getValue() < 1) {
            spinnerTime.setValue(1);
        }

    }//GEN-LAST:event_spinnerTimeStateChanged

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        //Obtenemos los segundos que se correrá
        this.runSeconds = (int) spinnerTime.getValue();
        tamVectorDatos = (int) (runSeconds / 0.1 + 1); //datos a guardar para graficar
        x = new double[tamVectorDatos];
        y = new double[tamVectorDatos];
        try {
            params = new CapturaParametros(Double.parseDouble(textNumerador.getText()), 1, Double.parseDouble(textT2.getText()));
            textResultados.setText("Resultados:\n"
                    + "Wd: " + params.getWd() + "\n"
                    + "Wn: " + params.getWn() + "\n"
                    + "Chi: " + params.getChi() + "\n"
                    + "Sigma: " + params.getSigma() + "\n\n"
                    + "Por lo tanto se trata de un " + params.getResult());
            systemType = params.getType();
            plotResult();
            
        } catch (Exception ex) {
            textResultados.setText("Error: " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelExample;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelType;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JPanel panelGraphics;
    private javax.swing.JPanel panelParams;
    private javax.swing.JPanel panelPlot;
    private javax.swing.JScrollPane scrollResultados;
    private javax.swing.JSpinner spinnerTime;
    private javax.swing.JTextField textNumerador;
    private javax.swing.JTextArea textResultados;
    private javax.swing.JTextField textT2;
    // End of variables declaration//GEN-END:variables
}
